export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const LOGIN_START = '[AUTH] LOGIN_START';
export const LOGIN_START_SUCCESS = '[AUTH] LOGIN_START_SUCCESS';
export const LOGIN_START_ERROR = '[AUTH] LOGIN_START_ERROR';
export const REGISTER_START = '[AUTH] REGISTER_START';
export const REGISTER_START_SUCCESS = '[AUTH] REGISTER_START_SUCCESS';
export const REGISTER_START_ERROR = '[AUTH] REGISTER_START_ERROR';

export const SET_PROJECT_TITLE = '[PROJECT] SET_PROJECT_TITLE';
export const SET_SELECTED_FILE = '[PROJECT] SET_SELECTED_FILE';
export const UPLOAD_FILE = '[PROJECT] UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = '[PROJECT] UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = '[PROJECT] UPLOAD_FILE_ERROR';
export const GENERATE_SAMPLE = '[PROJECT] GENERATE_SAMPLE';
export const GENERATE_SAMPLE_SUCCESS = '[PROJECT] GENERATE_SAMPLE_SUCCESS';
export const GENERATE_SAMPLE_ERROR = '[PROJECT] GENERATE_SAMPLE_ERROR';
export const ADD_NEW_FILTER = '[PROJECT] ADD_FILTER';
export const REMOVE_FILTER = '[PROJECT] REMOVE_FILTER';
export const TOGGLE_FILTER_ISACTIVE = '[PROJECT] TOGGLE_FILTER_ISACTIVE';
export const SET_TARGET_VARIABLE = '[PROJECT] SET_TARGET_VARIABLE';
