export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const LOGIN_START = '[AUTH] - LOGIN_START';
export const LOGIN_START_SUCCESS = '[AUTH] - LOGIN_START_SUCCESS';
export const LOGIN_START_ERROR = '[AUTH] - LOGIN_START_ERROR';
